### PR TITLE
ui: add multi fossilizers support

### LINKED ISSUE #21: Appending a segment twice in a row fails
### Expected behavior

Appending new segments from the 'segment' view should create a new segment and display it in the interface.

### Actual behavior

Appending a segment twice in a row from the 'segment' view fails and outputs the following error :
 ```
:4000/assets/vendor.js:37778 TypeError: Cannot read property 'getSegment' of undefined
    at Class.appendSegment (agent-ui.js:1540)
    at Class.appendSegmentThenViewNext (agent-ui.js:1772)
    at Backburner.join (:4000/assets/vendor.js:20546)
    at Function.run$1.join (:4000/assets/vendor.js:38160)
    at :4000/assets/vendor.js:28421
    at exports.flaggedInstrument (:4000/assets/vendor.js:37587)
    at :4000/assets/vendor.js:28420
    at Class.onSubmit (agent-ui.js:1330)
    at Backburner.join (:4000/assets/vendor.js:20540)
    at Function.run$1.join (:4000/assets/vendor.js:38160)
```

### Steps to reproduce the behavior

  1. ... go to `http://localhost:4000/<yourprocess>/maps` and create a new map
  2. ... click on `show segments` for the newly created map and click on any segment
  3. ... append a new segment (this should work the first time) and immediately try to append a new one, the error should appear (don't forget to select `preserve log` in your console settings to see the error).

### PR DESCRIPTION
**Pull request by simonvadee**
Each fossilizer's info linked to a process is now displayed on the process page

this commit also fixes #21

### CODE REVIEW

File: app/routes/process.js [hunk 1]
```diff
@@ -17,22 +17,24 @@
...
   model(params) {
-    return this
-      .get('stratumn')
+    return this.get('stratumn')
       .getAgent()
-      .then(agent =>
-        ({ processObject: agent.processes.find(p => p.name === params.process) })
-      );
+      .then(agent => {
+        console.log(agent.processes.find(p => p.name === params.process));
```
Comment (t-bast) [inline app/routes/process.js]: nit: remove the console logging ? I guess it was for your debug session right ?

Comment (simonvadee) [reply app/routes/process.js]: good catch!
